 %计算（某一种特征对应的）特征值，其中W,H代表检测窗口的像素数
function f = VecFeature(ftype, W, H)       

x = ftype(2); y = ftype(3); w = ftype(4); h = ftype(5);         %把对应的值从向量对应的位置去取出

switch ftype(1)         % ftyp（1）代表了矩形特征的类型
    case 1      %1x2
        f = VecBoxSum(x, y, w, h, W, H) - ...  %用...表示续行，下一行的代码和上一行是连着的
            VecBoxSum(x, y + h, w, h, W, H);
    case 2      %2x1
        f = VecBoxSum(x,   y, w, h, W, H) -...
            VecBoxSum(x+w, y, w, h, W, H);
    case 3      %3x1
        f = VecBoxSum(x,     y, w, h, W, H) +...
            VecBoxSum(x+2*w, y, w, h, W, H) -...
            VecBoxSum(x+w,   y, w, h, W, H);
    case 4      %1x3  新加
    f = VecBoxSum(x, y,     w, h, W, H) +...
        VecBoxSum(x, y+2*h, w, h, W, H) -...
        VecBoxSum(x, y+h,   w, h, W, H);    
    case 5     %2x2
        f = VecBoxSum(x,   y,   w, h, W, H) +...
            VecBoxSum(x+w, y+h, w, h, W, H) -...
            VecBoxSum(x+w, y,   w, h, W, H) -...
            VecBoxSum(x,   y+h, w, h, W, H);
    case 6     %1x4
        f = VecBoxSum(x,   y,       w, h, W, H) +...
            VecBoxSum(x,   y+3*h,   w, h, W, H) -...
            VecBoxSum(x,   y+h,     w, h, W, H) -...
            VecBoxSum(x,   y+2*h,   w, h, W, H);
end
